#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
COMPOSE_FILE="${ROOT_DIR}/docker-compose.generated.yml"
SECRETS_DIR="${ROOT_DIR}/secrets"
SECRET_FILE="${SECRETS_DIR}/codex_bridge_api_key"

DEFAULT_MODELS="coder,codex,gpt-5.5,gpt-5.4,gpt-5.4-mini,gpt-5.3-codex,gpt-5.3-codex-spark"

print_step() {
  printf '\n==> %s\n' "$1"
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'Fehlt: %s\n' "$1" >&2
    exit 1
  fi
}

prompt_default() {
  local prompt="$1"
  local default="$2"
  local value
  read -r -p "${prompt} [${default}]: " value
  printf '%s' "${value:-$default}"
}

prompt_yes_no() {
  local prompt="$1"
  local default="$2"
  local value
  read -r -p "${prompt} [${default}]: " value
  value="${value:-$default}"
  case "${value,,}" in
    y|yes|j|ja) return 0 ;;
    *) return 1 ;;
  esac
}

prompt_secret() {
  local prompt="$1"
  local value
  read -r -s -p "${prompt}: " value
  printf '\n' >&2
  printf '%s' "$value"
}

random_token() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    dd if=/dev/urandom bs=24 count=1 2>/dev/null | od -An -tx1 | tr -d ' \n'
  fi
}

detect_openwebui_network() {
  local container
  container="$(docker ps --format '{{.Names}}' | grep -E '^(open-webui|openwebui)$' | head -n 1 || true)"
  if [ -n "$container" ]; then
    docker inspect "$container" --format '{{range $name, $_ := .NetworkSettings.Networks}}{{println $name}}{{end}}' | head -n 1
    return 0
  fi
  printf 'ai_net'
}

python_cmd() {
  if command -v python3 >/dev/null 2>&1; then
    printf 'python3'
  elif command -v python >/dev/null 2>&1; then
    printf 'python'
  else
    printf ''
  fi
}

write_env_file() {
  if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  fi
  cat >"$ENV_FILE" <<EOF
# Generated by install.sh. Do not commit this file.
CODEX_BRIDGE_API_KEY=${CODEX_BRIDGE_API_KEY}
CODEX_BRIDGE_PUBLISHED_PORT=${CODEX_BRIDGE_PUBLISHED_PORT}
OPENWEBUI_DOCKER_NETWORK=${OPENWEBUI_DOCKER_NETWORK}
CODEX_BRIDGE_MODELS=${CODEX_BRIDGE_MODELS}
CODEX_BRIDGE_TIMEOUT=${CODEX_BRIDGE_TIMEOUT}
CODEX_BRIDGE_PROGRESS_INTERVAL=${CODEX_BRIDGE_PROGRESS_INTERVAL}
CODEX_BRIDGE_SECRET_FILE=${SECRET_FILE}
OPENWEBUI_BASE_URL=${OPENWEBUI_BASE_URL}
CODEX_BRIDGE_OPENWEBUI_URL=${CODEX_BRIDGE_OPENWEBUI_URL}
EOF
}

write_secret_file() {
  mkdir -p "$SECRETS_DIR"
  chmod 700 "$SECRETS_DIR"
  if [ -f "$SECRET_FILE" ]; then
    cp "$SECRET_FILE" "${SECRET_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  fi
  umask 077
  printf '%s\n' "$CODEX_BRIDGE_API_KEY" >"$SECRET_FILE"
}

write_compose_file() {
  if [ -f "$COMPOSE_FILE" ]; then
    cp "$COMPOSE_FILE" "${COMPOSE_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  fi
  cat >"$COMPOSE_FILE" <<'EOF'
services:
  codex-openai-bridge:
    build:
      context: .
    image: codex-openai-bridge:latest
    container_name: codex-openai-bridge
    restart: unless-stopped
    environment:
      CODEX_HOME: /home/codex/.codex
      CODEX_BRIDGE_HOST: 0.0.0.0
      CODEX_BRIDGE_PORT: 4010
      CODEX_BRIDGE_WORKDIR: /workspace
      CODEX_BRIDGE_API_KEY_FILE: /run/secrets/codex_bridge_api_key
      CODEX_BRIDGE_MODELS: ${CODEX_BRIDGE_MODELS}
      CODEX_BRIDGE_TIMEOUT: ${CODEX_BRIDGE_TIMEOUT:-900}
      CODEX_BRIDGE_PROGRESS_INTERVAL: ${CODEX_BRIDGE_PROGRESS_INTERVAL:-15}
    secrets:
      - codex_bridge_api_key
    ports:
      - "${CODEX_BRIDGE_PUBLISHED_PORT:-4010}:4010"
    volumes:
      - codex_home:/home/codex/.codex
      - codex_bridge_workspace:/workspace
    networks:
      - openwebui_network

volumes:
  codex_home:
  codex_bridge_workspace:

secrets:
  codex_bridge_api_key:
    file: ${CODEX_BRIDGE_SECRET_FILE}

networks:
  openwebui_network:
    name: ${OPENWEBUI_DOCKER_NETWORK}
    external: true
EOF
}

wait_for_health() {
  local url="http://127.0.0.1:${CODEX_BRIDGE_PUBLISHED_PORT}/health"
  local i
  for i in $(seq 1 30); do
    if curl -fsS "$url" >/dev/null 2>&1; then
      printf 'Bridge erreichbar: %s\n' "$url"
      return 0
    fi
    sleep 1
  done
  printf 'Bridge-Healthcheck war nicht rechtzeitig erreichbar: %s\n' "$url" >&2
  return 1
}

register_openwebui_provider() {
  local admin_token="$1"
  local py
  py="$(python_cmd)"
  if [ -z "$py" ]; then
    printf 'Python wurde nicht gefunden; Provider-Registrierung übersprungen.\n' >&2
    return 1
  fi
  OPENWEBUI_ADMIN_TOKEN="$admin_token" \
  CODEX_BRIDGE_API_KEY="$CODEX_BRIDGE_API_KEY" \
  CODEX_BRIDGE_MODELS="$CODEX_BRIDGE_MODELS" \
  "$py" "${ROOT_DIR}/scripts/configure_openwebui_provider.py" \
    --openwebui-url "$OPENWEBUI_BASE_URL" \
    --bridge-url "$CODEX_BRIDGE_OPENWEBUI_URL"
}

print_step "Voraussetzungen prüfen"
require_command docker
require_command curl
docker compose version >/dev/null

detected_network="$(detect_openwebui_network)"
generated_key="$(random_token)"

print_step "Konfiguration abfragen"
OPENWEBUI_BASE_URL="$(prompt_default 'OpenWebUI-URL vom Installationshost aus' 'http://localhost:3000')"
OPENWEBUI_DOCKER_NETWORK="$(prompt_default 'Docker-Netz, in dem OpenWebUI läuft' "$detected_network")"
CODEX_BRIDGE_OPENWEBUI_URL="$(prompt_default 'Interne Bridge-URL aus Sicht des OpenWebUI-Containers' 'http://codex-openai-bridge:4010/v1')"
CODEX_BRIDGE_PUBLISHED_PORT="$(prompt_default 'Host-Port für Bridge-Healthcheck und lokale Tests' '4010')"
CODEX_BRIDGE_MODELS="$(prompt_default 'Kommagetrennte Modell-IDs, die die Bridge anbieten soll' "$DEFAULT_MODELS")"
CODEX_BRIDGE_TIMEOUT="$(prompt_default 'Timeout pro Codex-Aufruf in Sekunden' '900')"
CODEX_BRIDGE_PROGRESS_INTERVAL="$(prompt_default 'Sekunden zwischen sichtbaren Fortschrittsmeldungen im Streaming' '15')"
CODEX_BRIDGE_API_KEY="$(prompt_default 'Lokaler Bridge-API-Key für OpenWebUI Provider' "$generated_key")"

print_step "Dateien erzeugen"
write_env_file
write_secret_file
write_compose_file
mkdir -p "${ROOT_DIR}/workspace"
printf 'Erzeugt: %s\n' "$ENV_FILE"
printf 'Erzeugt: %s\n' "$SECRET_FILE"
printf 'Erzeugt: %s\n' "$COMPOSE_FILE"

print_step "Compose prüfen"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" config >/dev/null
printf 'Compose-Konfiguration ist gültig.\n'

if prompt_yes_no 'Image jetzt bauen?' 'ja'; then
  print_step "Image bauen"
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" build
fi

if prompt_yes_no 'Container jetzt starten?' 'ja'; then
  print_step "Container starten"
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d
  wait_for_health || true
fi

if prompt_yes_no 'Codex Login im Container jetzt starten? Nur nötig, wenn dieses Docker-Volume noch nicht authentifiziert ist.' 'nein'; then
  print_step "Codex Login"
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" run --rm --entrypoint codex codex-openai-bridge login
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" restart codex-openai-bridge || true
fi

if prompt_yes_no 'Bridge automatisch in OpenWebUI als Responses-Provider registrieren?' 'ja'; then
  print_step "OpenWebUI Provider registrieren"
  OPENWEBUI_ADMIN_TOKEN_VALUE="$(prompt_secret 'OpenWebUI Admin API-Key (wird nicht gespeichert)')"
  register_openwebui_provider "$OPENWEBUI_ADMIN_TOKEN_VALUE"
fi

print_step "Fertig"
printf 'Bridge Compose: %s\n' "$COMPOSE_FILE"
printf 'OpenWebUI Provider URL: %s\n' "$CODEX_BRIDGE_OPENWEBUI_URL"
printf 'OpenWebUI Provider API-Key: Wert aus CODEX_BRIDGE_API_KEY in .env\n'
printf 'Nächste Befehle:\n'
printf '  docker compose --env-file .env -f docker-compose.generated.yml ps\n'
printf '  curl -H "Authorization: Bearer $CODEX_BRIDGE_API_KEY" http://localhost:%s/v1/models\n' "$CODEX_BRIDGE_PUBLISHED_PORT"
